# Generated by Django 4.0.1 on 2023-01-02 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0002_rename_td_user_id_tguser_tg_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='tg_chat_id',
            field=models.BigIntegerField(verbose_name='id чата'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tg_user_id',
            field=models.BigIntegerField(verbose_name='идентификатор пользователя'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
