# Generated by Django 4.0.1 on 2023-01-03 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0004_alter_tguser_tg_chat_id_alter_tguser_tg_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='tg_username',
            field=models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='tg username'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
